import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JMenu;
import java.awt.event.KeyEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JButton;

/**
 * This game is a project in "Computer Graphics".
 * @author Mergim Rama
 * @date: 06/05/2016
 */
public class BreakoutGame extends JFrame {

	/**
	 * Automatically generated by eclipse
	 */
	private static final long serialVersionUID = -6866130723085254645L;
	private JMenu mnFile;
	public static JMenuItem mntmRestart;
	public static JPanel panelSouth;
	public static JButton btnRestart;
	
	public BreakoutGame() {
		super("Breakout Game");
		
		JMenuBar menuBar = new JMenuBar();
		setJMenuBar(menuBar);
		
		mnFile = new JMenu("File");
		menuBar.add(mnFile);
		mnFile.setMnemonic(KeyEvent.VK_F);
		
		mntmRestart = new JMenuItem("Restart");
		mntmRestart.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				dispose();
				new BreakoutGame();
			}
		});
		mntmRestart.setMnemonic(KeyEvent.VK_R);
		mnFile.add(mntmRestart);
		
		JMenuItem mntmExit = new JMenuItem("Exit");
		mntmExit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				System.exit(0);
			}
		});
		mntmExit.setMnemonic(KeyEvent.VK_E);
		mnFile.add(mntmExit);
		
		JMenu mnHelp = new JMenu("Help");
		mnHelp.setMnemonic(KeyEvent.VK_H);
		menuBar.add(mnHelp);
		
		JMenuItem mntmAbout = new JMenuItem("About");
		mntmAbout.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				JOptionPane.showMessageDialog(null,
						"Mergim Rama ©");
			}
		});
		mntmAbout.setMnemonic(KeyEvent.VK_A);
		mnHelp.add(mntmAbout);
		
		initUI();
	}
	
	private void initUI() {
		Board board = new Board();
		board.setBackground(Color.ORANGE);
		getContentPane().setLayout(new BorderLayout());
		getContentPane().add(board, BorderLayout.CENTER);
		
		panelSouth = new JPanel();
		panelSouth.setVisible(false);
		panelSouth.setFocusable(false);
		panelSouth.setRequestFocusEnabled(false);
		panelSouth.setBackground(Color.ORANGE);
		getContentPane().add(panelSouth, BorderLayout.SOUTH);
		
		btnRestart = new JButton("Restart");
		btnRestart.setRequestFocusEnabled(false);
		btnRestart.setFocusable(false);
		btnRestart.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				dispose();
				new BreakoutGame();
			}
		});
		panelSouth.add(btnRestart);
		
		JButton btnExit = new JButton("Exit");
		btnExit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				System.exit(0);
			}
		});
		panelSouth.add(btnExit);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setSize(Sizes.WIDTH + 6, Sizes.HEIGHT + 60);
		setLocationRelativeTo(null);
		setResizable(false);
		setVisible(true);
	}
	
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			
			@Override
			public void run() {
				// TODO Auto-generated method stub
				BreakoutGame game = new BreakoutGame();
				try {
					UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
				} catch (IllegalAccessException | ClassNotFoundException | InstantiationException | UnsupportedLookAndFeelException e) {
					JOptionPane.showMessageDialog(game, e.getMessage());
				}
				game.setVisible(true);
			}
		});
	}
}
